steps:
- name: gcr.io/cloud-builders/gcloud
  args: [config, get-value, account]
- name: gcr.io/cloud-builders/git
  args: [fetch, --unshallow, --tags]
- name: gcr.io/cloud-builders/npm:current
  args: [install]
- name: gcr.io/cloud-builders/npm:current
  dir: functions
  args: [install]
- name: gcr.io/cloud-builders/npm:current
  args: [run, deploy]
  env:
  - ENVIRONMENT=${_ENVIRONMENT}
- name: gcr.io/cloud-builders/npm:current
  args: [run, update-dev-database]

substitutions:
    _ENVIRONMENT: dev

artifacts:
  objects:
    location: gs://chromebooks-in-deutschland-logs/$BUILD_ID
    paths: [backup.json]